In [60]:
import torch

from naslib.search_spaces.nasbench101 import graph
from naslib import utils
from naslib.utils import setup_logger
from naslib.utils import get_dataset_api
from naslib.search_spaces.core.query_metrics import Metric

In [58]:
dataset_api = get_dataset_api('nasbench101', None)

Loading dataset from file... This may take a few minutes...
Loaded dataset in 7 seconds


In [102]:
# load the search space
search_space = graph.NasBench101SearchSpace()

def init_all(model, init_func, *params, **kwargs):
    for p in model.parameters():
        init_func(p, *params, **kwargs)

In [107]:
# let's pick one architecture
arch = search_space.clone()
arch.sample_random_architecture(dataset_api=dataset_api)
arch.parse()

x = torch.randn(2, 3, 32, 32)
for i in range(3):    
    init_all(arch, torch.nn.init.normal_, mean=0., std=1.)
    result = arch(x)
    print(result)

tensor([[-14.3642,  -1.2093,  48.0616, -38.5363, -94.7019,  40.1212, -23.1031,
          41.3809,  16.5359,  29.0815],
        [-34.5444, -21.6482,  47.4450, -26.6883, -75.4504,  44.0432, -19.0839,
          42.8978,   5.2774,  23.6642]], grad_fn=<AddmmBackward0>)
tensor([[  4.2589, -43.9412,  80.2374,  13.2795, -35.8382, -19.0611, -14.5941,
          -9.6030, -21.1214, -56.0678],
        [  1.6917, -29.9484,  79.4799,  22.8502, -48.0461,   6.0933, -15.4071,
          -4.1062,   0.2945, -44.4002]], grad_fn=<AddmmBackward0>)
tensor([[ 11.8846,   7.3094,  -7.8517,  30.2605, -93.3437, -12.7218, -69.4709,
           6.9822,  12.7760, -25.5242],
        [  2.9314,  -3.0508,  -0.6746,  34.4199, -71.9115,  12.9910, -86.0084,
          -6.6435,  26.7627, -26.8809]], grad_fn=<AddmmBackward0>)
